In [408]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [409]:
df = pd.read_excel('/content/drive/MyDrive/Colab Notebooks/Final Project - Brand Audit 2023/RAW ALL DATA BRAND AUDIT 2023.xlsx')

In [410]:
df

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12
0,Brand Name,Parent Company,If Parent Company does not appear automaticall...,Item Description,Type of Product,Type of Material,Layers,Total Count,City,Provinces,Time of Audit,Type of Audit,Specifics of Audit
1,PUTRI PANDA,Putri Panda,NaN,FOOD,FP,PET,SL,6,Cilacap,Central Java,2023-09-09 00:00:00,Outdoor,Coast/Shoreline
2,ABC,Santos Jaya Abadi,NaN,COFFE,FP,PET,SL,12,Cilacap,Central Java,2023-09-09 00:00:00,Outdoor,Coast/Shoreline
3,KAPAL API,Santos Jaya Abadi,NaN,COFFE,FP,PET,SL,3,Cilacap,Central Java,2023-09-09 00:00:00,Outdoor,Coast/Shoreline
4,KOPI GOOD DAY,NaN,Santos Jaya Abadi,COFFE,FP,PET,SL,3,Cilacap,Central Java,2023-09-09 00:00:00,Outdoor,Coast/Shoreline
...,...,...,...,...,...,...,...,...,...,...,...,...,...
3791,HONEY LEMON,NaN,UNKNOWN,FOOD PACKAGING,FP,PS,ML,1,East Lombok,West Nusa Tenggara,2023-09-29 00:00:00,Outdoor,Mountain
3792,MARIMAS,Marimas Putera Kencana,NaN,FOOD PACKAGING,FP,PS,ML,2,East Lombok,West Nusa Tenggara,2023-09-29 00:00:00,Outdoor,Mountain
3793,JAS JUS,Wings,NaN,FOOD PACKAGING,FP,PS,SL,1,East Lombok,West Nusa Tenggara,2023-09-29 00:00:00,Outdoor,Mountain
3794,MILO,Nestle,NaN,FOOD PACKAGING,FP,PS,ML,3,East Lombok,West Nusa Tenggara,2023-09-29 00:00:00,Outdoor,Mountain
3795,KAPAL API,Santos Jaya Abadi,NaN,FOOD PACKAGING,FP,PS,ML,3,East Lombok,West Nusa Tenggara,2023-09-29 00:00:00,Outdoor,Mountain

# Menjadikan baris bertama sebagai nama kolom

In [411]:
df.columns = df.iloc[0]
df = df[1:]
df = df.reset_index(drop=True)
df

,Brand Name,Parent Company,"If Parent Company does not appear automatically or needs correction, please add here.",Item Description,Type of Product,Type of Material,Layers,Total Count,City,Provinces,Time of Audit,Type of Audit,Specifics of Audit
0,PUTRI PANDA,Putri Panda,NaN,FOOD,FP,PET,SL,6,Cilacap,Central Java,2023-09-09 00:00:00,Outdoor,Coast/Shoreline
1,ABC,Santos Jaya Abadi,NaN,COFFE,FP,PET,SL,12,Cilacap,Central Java,2023-09-09 00:00:00,Outdoor,Coast/Shoreline
2,KAPAL API,Santos Jaya Abadi,NaN,COFFE,FP,PET,SL,3,Cilacap,Central Java,2023-09-09 00:00:00,Outdoor,Coast/Shoreline
3,KOPI GOOD DAY,NaN,Santos Jaya Abadi,COFFE,FP,PET,SL,3,Cilacap,Central Java,2023-09-09 00:00:00,Outdoor,Coast/Shoreline
4,POP MIE,Indofood,NaN,NOODLES,FP,PS,SL,1,Cilacap,Central Java,2023-09-09 00:00:00,Outdoor,Coast/Shoreline
...,...,...,...,...,...,...,...,...,...,...,...,...,...
3790,HONEY LEMON,NaN,UNKNOWN,FOOD PACKAGING,FP,PS,ML,1,East Lombok,West Nusa Tenggara,2023-09-29 00:00:00,Outdoor,Mountain
3791,MARIMAS,Marimas Putera Kencana,NaN,FOOD PACKAGING,FP,PS,ML,2,East Lombok,West Nusa Tenggara,2023-09-29 00:00:00,Outdoor,Mountain
3792,JAS JUS,Wings,NaN,FOOD PACKAGING,FP,PS,SL,1,East Lombok,West Nusa Tenggara,2023-09-29 00:00:00,Outdoor,Mountain
3793,MILO,Nestle,NaN,FOOD PACKAGING,FP,PS,ML,3,East Lombok,West Nusa Tenggara,2023-09-29 00:00:00,Outdoor,Mountain
3794,KAPAL API,Santos Jaya Abadi,NaN,FOOD PACKAGING,FP,PS,ML,3,East Lombok,West Nusa Tenggara,2023-09-29 00:00:00,Outdoor,Mountain

In [412]:
df.columns

Index(['Brand Name', 'Parent Company',
       'If Parent Company does not appear automatically or needs correction, please add here.',
       'Item Description', 'Type of Product', 'Type of Material', 'Layers',
       'Total Count', 'City', 'Provinces', 'Time of Audit', 'Type of Audit',
       'Specifics of Audit'],
      dtype='object', name=0)

# Menghapus kolom yang tidak diperlukan

In [413]:
df = df.drop(columns=['Item Description', 'Type of Audit'])
display(df.head())

,Brand Name,Parent Company,"If Parent Company does not appear automatically or needs correction, please add here.",Type of Product,Type of Material,Layers,Total Count,City,Provinces,Time of Audit,Specifics of Audit
0,PUTRI PANDA,Putri Panda,NaN,FP,PET,SL,6,Cilacap,Central Java,2023-09-09 00:00:00,Coast/Shoreline
1,ABC,Santos Jaya Abadi,NaN,FP,PET,SL,12,Cilacap,Central Java,2023-09-09 00:00:00,Coast/Shoreline
2,KAPAL API,Santos Jaya Abadi,NaN,FP,PET,SL,3,Cilacap,Central Java,2023-09-09 00:00:00,Coast/Shoreline
3,KOPI GOOD DAY,NaN,Santos Jaya Abadi,FP,PET,SL,3,Cilacap,Central Java,2023-09-09 00:00:00,Coast/Shoreline
4,POP MIE,Indofood,NaN,FP,PS,SL,1,Cilacap,Central Java,2023-09-09 00:00:00,Coast/Shoreline

#Menggabungkan data parent company dari dua kolom

In [414]:
df.columns

Index(['Brand Name', 'Parent Company',
       'If Parent Company does not appear automatically or needs correction, please add here.',
       'Type of Product', 'Type of Material', 'Layers', 'Total Count', 'City',
       'Provinces', 'Time of Audit', 'Specifics of Audit'],
      dtype='object', name=0)

In [415]:
df['Parent Company'] = df['Parent Company'].fillna(df['If Parent Company does not appear automatically or needs correction, please add here.'])
df['Parent Company'] = df['Parent Company'].fillna('Unknown')
df = df.drop(columns=['If Parent Company does not appear automatically or needs correction, please add here.'])

current_columns = df.columns.tolist()
if 'Parent Company' in current_columns:
    current_columns.remove('Parent Company')

brand_name_index = current_columns.index('Brand Name')
new_column_order = current_columns[:brand_name_index + 1] + ['Parent Company'] + current_columns[brand_name_index + 1:]
df = df[new_column_order]
display(df.head())

,Brand Name,Parent Company,Type of Product,Type of Material,Layers,Total Count,City,Provinces,Time of Audit,Specifics of Audit
0,PUTRI PANDA,Putri Panda,FP,PET,SL,6,Cilacap,Central Java,2023-09-09 00:00:00,Coast/Shoreline
1,ABC,Santos Jaya Abadi,FP,PET,SL,12,Cilacap,Central Java,2023-09-09 00:00:00,Coast/Shoreline
2,KAPAL API,Santos Jaya Abadi,FP,PET,SL,3,Cilacap,Central Java,2023-09-09 00:00:00,Coast/Shoreline
3,KOPI GOOD DAY,Santos Jaya Abadi,FP,PET,SL,3,Cilacap,Central Java,2023-09-09 00:00:00,Coast/Shoreline
4,POP MIE,Indofood,FP,PS,SL,1,Cilacap,Central Java,2023-09-09 00:00:00,Coast/Shoreline

In [416]:
df['Parent Company']

0                  Putri Panda
1            Santos Jaya Abadi
2            Santos Jaya Abadi
3            Santos Jaya Abadi
4                     Indofood
                 ...
3790                   UNKNOWN
3791    Marimas Putera Kencana
3792                     Wings
3793                    Nestle
3794         Santos Jaya Abadi
Name: Parent Company, Length: 3795, dtype: object

In [417]:
df['Parent Company'].unique()

array(['Putri Panda', 'Santos Jaya Abadi', 'Indofood', 'Wings',
       'Niaga Nusa Abadi', 'Sumatra Tobacco Trading Company',
       'Gudang Garam Tbk.', 'Djarum', 'Harum', 'Tapal Kuda Kencana',
       'Siantar Top', 'Stanly Trijaya Mandiri', 'Indonesia Bakery Family',
       'Nippon Indosari Corpindo', 'Unknown', 'Angri Wangi Indonesia',
       'Apical Group', 'Colgate-Palmolive', 'Head & Shoulder',
       'phrong intertrade co ltd', 'Danone', 'Bina Karya Prima',
       'Uni-Charm Indonesia', 'PROTEX', 'Nabati', 'Tudung Group',
       'Tirta Investama', 'Mayora Indah', 'PT Lion Wings',
       'Perfetti van Melle', 'Agel Langgeng', 'Orang Tua', 'Sasa Inti',
       'Ajinomoto', 'Gandhi Spices Pvt. Ltd.',
       'Kao Corporation Chemicals company', 'Godefroy',
       'PT Macroprima Panganutama', 'Garuda Food', 'Unbranded',
       'Unicharm', 'Tanobel Food', 'So Good', 'Bintang Toedjoe',
       'Sidomuncul', 'FrieslandCampina', 'Deltomed Laboratories',
       'Unilever', 'Ultrajaya', 'Nabati Group.', 'Yakult',
       'Simba Indosnack Makmur', 'Ultra Prima Abadi', 'Internusa Food',
       'Pacific Food Indonesia', 'Tiga Pilar Sejahtera', 'Yupindo',
       'The Coca-Cola Company', 'unilever', 'Madurasa Unggulan Nusantara',
       'PT Graha Kerindo Utama', 'Enesis Group', 'Forisa Nusa Persada',
       'PT Konimex', 'Ranjani Jaya Lestari', 'PT ABC President Indonesia',
       'HM Sampoerna, Tbk', 'Delfi limited', 'PT Niramas Utama',
       'Universal Robina Corporation', 'Lotte Confectionary Co',
       'Gumindo', 'Delfi Ltd.', 'Bronson', 'Simba',
       'PT Gudang Baru Berkah', 'Philip Morris International',
       'Perusahaan Rokok Bahagia', 'PT Mayora Indah Tbk',
       'British American Tobacco', 'Pandaria Makmur (Kiko Fact)',
       'Wong Coco', 'Djojonegoro', 'PT Ultra Sakti', "Arnott's",
       'PT Pesta Pora Abadi', 'PT Nissin Biscuit Indonesia', 'Heinz',
       'PT Jaya Utama Santikah', 'sinar Jaya Perkasa', 'Aice',
       'Wings Indonesia', 'Java Prima Abadi', 'Musim Mas Group',
       'Marimas Putera Kencana',
       'PT Java Egg Specialities (Cimory Group)', 'Multisari',
       'Megasari Makmur', 'Nabati Snack', 'Gumindo Bogamanis',
       'Japfa Limited', 'Dua Kelinci', 'Sugar Group', 'Wilmar Group',
       'ASW Food', 'Tango', 'CV Bumi Waras', 'PT Daesang Agung Indonesia',
       'Otsuka', 'Sari Murni Group', 'CV Nana Abadi', 'Jordan bakery',
       'SMART', 'PT Agrinesia Raya Sleman', 'Kalbe Farma Tbk',
       'Indurstri Jamu dan Farmasi Sido Muncul', 'Sinar Sosro',
       'BIOCHEM India', 'Forisa', 'PT Motasa Indonesia', 'NutriFood',
       'Imperial Brands', 'Glico', 'Mayora Inda', 'PT Global Dairi Alam',
       "L'Oreal", 'Procter & Gamble', 'Sumber Alfaria Trijaya',
       'PT Elson Bernardi', 'Smart', 'Nutri-Asia Inc.',
       'Premier Marketing Public Company Limited', 'Dongsuh Foods',
       'Tong Tji Tea Indonesia ', 'Mountain Dairy', 'Konimex',
       'Sayap Mas Utama', '7 Eleven', 'PT Eagle Indo Pharma',
       'Paragon Technology', 'Lion Wings', 'Salim Ivomas Pratama',
       ' PT SC Johnson and Son Indonesia', 'Wismilak Group',
       'CV Top Asli', 'Tirta Agung Wijaya', 'Nestle', 'Sari Murni',
       'Mommilk Group Indonesia', 'PT KOI Café Indonesia', 'Gudang Baru',
       'Sappe', 'CV Sejahtera Malang', 'Unifam', 'Gloria Bisco',
       'PT Catur Wangsa Indah', 'PT Charoen Pokphand Indonesia Tbk',
       'PT Sekar Laut', 'Indomaret', 'PT Softex Indonesia', 'Cussons',
       'PT Semen Padang', 'PT. Pacific Food Indonesia',
       'Salim Ivomas Pratama Tbk.', 'PT UNIChemCandi Indonesia', 'Pran',
       'PT Natural Nusantara', 'APP Sinarmas', 'Alfamart', 'Meiji',
       'PT Balaraja Barat Indah', 'Jordan Bakery', 'Asia Kamond Food',
       'Aneka Boga Nusantara', 'Ceres', 'PT Kino Indonesia',
       'Interfood Sukses Jasindo', 'Sinergi Adimitra Jaya',
       'Kraft Indonesia', 'PT KARA SANTAN PERTAMA', 'Tempo Scan Pacific',
       'BFY Brands', 'PT Super Wahana Tehno',
       'PT. Serena Indopangan Industri', 'Sekar Sari Snack Cikarang',
       'Gopek Cipta Utama', 'Asia Pulp & Paper Group', 'So Good Food',
       'CV Bintang Karya Rasa', 'OK Foods', 'Kino Sentra Industrindo',
       'Sari wangi', 'ABC', 'Cocola', 'PepsiCo', 'Morinaga',
       'Sinar Kencana Agung', 'Monde M.Y. San Corporation',
       'Sumber Kopi Prima', 'PT Gelora Nusantara Persada',
       'Tokinori Kilau Perkasi', 'fashion food co.,ltd.',
       'Campbell Soup Company', 'Godrej Indoneisa',
       'PT Kutai Refinery Nusantara', 'Liwayway Holdings Company Limited',
       'Kobe', 'ABC President', 'Local Brand',
       'National Coconut Corporation', 'Sinde', 'sari enesis indah',
       'Batu Karang Indonesia', 'CV. Indoniaga kab. TTU', 'Ichitan Group',
       'Mega global food', 'LG Household & Health Care',
       'Indraco Global Indonesia', 'RBC', 'PT United Waru Biscuit',
       'Starsun Kreasindo Industry', 'PT Santos Jaya Abadi',
       'Kris Plastics Private Ltd.', 'PT BRU',
       'PT GarudaFood Putra Putri Jaya Tbk', 'Ferrero Group',
       'Khong Guan', 'PT Indraco Jaya Perkasa Gresik',
       'Astra Honda Motor (AHM)', 'PT Pertamina Lubricants',
       'PT Dutamasindo Labora Jaya ', 'Bronson Prima Industri',
       'Sekar Laut', 'PT Pusan Manis Gula', 'Sari Enesis Indah',
       'Bonafide Water', 'PT Motto Beringin Abadi', 'Frisian Flag',
       'Van Melle', 'Sigaret Kretek Mesin', 'PT Gudang Baru',
       'Sido Muncul', 'PT Anugrah Indofood Barokah Makmur',
       'Johnson & Johnson', 'Djojonegoro C-1000', 'UNKNOWN',
       'PT.Alam Indah', 'PT. AM JAYAPURA Robongholo Nanwani',
       'Britania Industries Ltd.', 'tirta amarta jaya sentosa',
       'Dilatama Karya (AMDK) Puroxa', 'Tandaria Makmur', 'INDOFOOD',
       'ABC President Indonesia', 'Coca Cola Limited', 'Paldo Co',
       'Yuasa Battery Indonesia', 'PT. Johnson Home Hygiene Products',
       'PT Pertamina (Persero)', 'PT BINA KARYA PRIMA',
       'Konimex Pharmaceutical Laboratories', 'CV Mitra Inti Jaya',
       'AGRO GROUP', 'SHACIHATA', 'PT WATERU NATURAL ALKALINDO',
       'Wiesgart', 'Tirta Logam Tunggal', 'TASTY SINGAPORE',
       'Korea Tomorrow & Global Corporation', 'WINGS FOOD',
       'CV Arira Pangindo', 'PT PID ONGKOWIDJOJO', 'GarudaFood',
       'PT ABC PRESIDENT INDONESIA', 'PT Tirta Fresindo jaya', 'CV. Anzi',
       'Air Gangga Dewata Alami', 'CV Gani Langit', 'Argus Rezky Pratama',
       'GlaxoSmithKline', 'CV. TIRTA AMERTA',
       'Indofood CBP Sukses Makmur Tbk', 'PT. JAYA UTAMA SANTIKAH',
       'Gunung Subur Sejahtera', 'PT. ROCHA SINERGI PERSADA',
       'PT. SYNERGI ANTAR NUSADA', 'PT. VERRA INTER PANGAN', 'MORINAGA',
       'Tipco', 'YoyiC Dairy', 'ORANG TUA',
       'PT. ZISHENG PACIFIC TRADING ', 'Mandom corp.', 'Paragon',
       'Atlantic Biruraya', 'PT. MURNI AIK SUKSES',
       'PT. KELLY INTERNATIONAL COSMETICS', 'Eagle Indo Pharma',
       'PT. SINAR SOSRO', 'Tirta Rezeki Dewata', 'Sinde Budi Sentosa',
       'PT. SANTOS JAYA ABADI', 'PT. JUNYI JAYA INDONESIA', 'Lassonde',
       'Interbis Sejahtera', 'WINGS', 'PT. ABC PRESIDENT INDONESIA',
       'UD. LUMBUNG MAS', 'Aji Frozen USA Corporation', 'POLYTEX',
       'CV DHIAN MANDIRI', 'PT. INDOSARI MANDIRI', 'CV Gangsar',
       'Surya Pratista Hutama', 'CV. PUSAKA BALI PERSADA',
       'Mars, Incorporated', 'unbranded', 'Narmada Awet Muda',
       'PT. CHAROEN POKPHAND INDONESIA',
       'PT. INDRACO JAYA PERKASA GRESIK', 'PT. ANEKA INTI BUMI TANGERANG',
       'Pie Susu Chandra', 'ECHO', 'UD. HARTA LAUT', 'SAMYANG FOODS',
       'PT. GOOD SPICE FOOD BANDUNG', 'Lemonilo',
       'Sinar Pangan Sejahtera', 'COKRO GROUP', 'CV. NEA BEAUTY',
       'PT. PANCA PEDJA SEJAHTERA', 'PT. WIHADIL', 'Indra Mukti Segara',
       'For East', 'Groupe Alma', 'Kino', 'PT. KONIMEX',
       'PT. ALLOY MANDIRI FOOD', 'Bentoel TBK', 'Isoma Malang',
       'Red Bull', 'PT. KAPAL API GLOBAL', 'Bima Karya Prima',
       'Sumber Tirta Pamenang', 'Meiji Holdings Co., Ltd',
       'cv ribut snack', 'PT. SERENA INDOPANGAN INDUSTRI', 'Tong garden',
       'PT. MANOHARA ASRI', 'Green Asia Food', 'AFC LIFESCIENCE',
       'Jaya Abadi', 'PT. BRU', 'PT. SEKAR LAUT', 'CRU Indonesia',
       'UNIVERSAL INDOFOOD', 'PT. DEWATA SUKSES PERKASA',
       'Hershey Company', 'Sari Murni Jaya', 'Abadi Maju Sigaret',
       'Djarum Indonesia', 'PT. BENTOEL', 'PT. BINA KARYA PRIMA',
       'PT. PUSAN MANIS MULIA', 'PT. SARI AGROTAMA PERSADA',
       'Rubber Snack Industry', 'SARI MURNI GROUP', 'PT PERMATA INDO KAV',
       'Indolakto', 'PT. UBM', 'Lion Corporation',
       'PT. INDAH JAYA INDONESIA', 'European Snack Food Co.,Ltd.',
       'MAYORA INDAH', 'Kokola', 'INDOFOOD FORTUNA MAKMUR',
       'PT. MONDELEZ INDONESIA MANUFACTURING', 'PT. SAKTISETIA SANTOSA',
       'PT. UNION FOODS', 'PT. GUMINDO BOGA MANIS',
       'Asia Health Energi Beverages', 'PT. Canning Indonesian Products ',
       'PT. Dewata Kencana Distribusi', 'Jakarana Tama', 'NONGSHIM',
       'PT RADJAWALI FOOD', 'PT KOBE', 'PT. SARANA SUMBER TIRTA',
       'PT. SUMBER MINERAL INDAH', 'PT. TRISAKTI MAKMUR ABADI',
       'PERUMDA AIR MINUM TIRTA RAHARJA', 'CV Tirta Mekar KUNINGAN',
       'CV. PRAJA MANDIRI', 'Indomultimas Perkasa',
       'Indomarco Prismatama', 'YOGYA', 'Holland Bakery Indonesia',
       'PT. Liwayway', 'PT CitraDimensi Arthali',
       'CV pangan berkah sentosa', 'PT bamboe indonesia',
       'PT Petra Sejahtera Abadi ', 'PT TRIO RASA MAS',
       'PT. Pandowo Utomo Food', 'PT Sukanda Djaya',
       'PT Indonesia Bakery Family', 'PT Indofood CBP Sukses Makmur Tbk',
       'Calbee Wings', 'PT. Indofood Fritolay Makmur',
       'PT. Harum Alam Segar Gersik', 'WINGSFOOD', 'FairPack Indonesia',
       'PT anugrah persada alam', 'PT. SARI INCOFOOD CORPORATION', 'HNI',
       'PT.Oxy Indomed', 'PT Torabika Eka Semesta',
       'PT Amidis Tirta Mulia', 'Suntory Beverage & Food',
       'INDOMARET GRUP', 'PT Bumi Berkah Boga', 'PT. TOYAMILINDO',
       'PT. Global Dairi Alami', 'Kalbe Farma', 'PT Glico Indonesia',
       'GARUDA FOOD', 'Henkel AG & Co. KGaA', 'PT. Yutaka Asia Indonesia',
       'PT. Indomarco Prismatama',
       'Thai Vegetable Oil Public Company Limited',
       'PT. Selahonje Jaya Mandiri', 'PT Multi Sari Sedap',
       'Karunia alam segar', 'PT Salim Ivomas Pratama Tbk',
       'PT. Taru Martani\xa0', 'Tirta Alam', 'PT mayora',
       'Asia Health Energy Beverages', 'PT Dellifood Sentosa Corpindo',
       'PT Sentrafood Indonesia', 'UNBRANDED',
       'PT Tri Sakti Purwosari Makmur', 'Nojorono Tobacco International',
       'Philip Morris USA', 'Reynolds American, Inc.',
       'PT Merapi Agung lestari', 'HM SHAMPOOerna, Tbk',
       'PT HM SHAMPOOerna Tbk', 'DJARUM',
       'PT Armando Intertobacco Industry', 'djarum', 'Cakra Guna Cipta',
       'PT\xa0SEJUK malang', 'Momogi', 'NABATI', 'PT. Nirwana Lestari',
       'PT. Serena Cafetaria Rasa', 'RFM Corporation', 'JAPFA',
       'PT DUTAMASINDO LABORA JAYA', 'PT. Sekar Bumi',
       'PT Petra Sejahtera Abadi', 'BELFOODS', 'PT.Porto Food Indonesia',
       'PT. Dagsap Endura', 'Cheroen Pokphand Indonesia Tbk', 'PT ABC',
       'IndoFOOD PACKAGING ', 'PT universal indoFOOD PACKAGING  product',
       'PT. Internusa FOOD PACKAGING ', 'PT. Kiko Energy Indonesia',
       'PT. Yupi Indo Jelly Gum', 'Tanobel FOOD PACKAGING ',
       'PT aini Sejahtera', 'Indocafe', 'Aica Indria',
       'PT Bintang Toedjoe', 'Motasa Indonesia', 'Softex Indonesia',
       'Dongsuh FOOD PACKAGING s', 'PT suntory Garuda BOTTLE',
       'PT. Bronson Prima Industri', 'PT sinar sosro',
       'PT. Ulee Kareng coffe', 'Sanhiang Perkasa',
       'Garuda FOOD PACKAGING ', 'PT Hanjaya Mandala Sampoerna Tbk',
       'PT Tirta Fresindo Jaya',
       'PT Ultrajaya Milk Industry & Trading Company TBK',
       'PT indoFOOD PACKAGING  sukses makmur',
       'PT. Medan Jaya Pangan Mutu', 'PT. Siantar Top, Tbk',
       'PT sintong abadi', 'PT\xa0Jaya Utama Santikah',
       'ASW FOOD PACKAGING ', 'PT. Barclay Products',
       'PT glico indonesia', 'NutriFOOD PACKAGING ',
       'PT INDOCARE CITRAPASIFIC', 'PT SINAR SOSRO',
       'CV TIRTA MITRA SEJATI', 'PT LUNA BOGA NARAYAN',
       'PT DIFUSI GOLDEN UTAMA', 'PT GUNACIPTA MULTIRASA', 'Mandom',
       'TEMPO SCAN PACIFIC', 'PT SARI INCOFOOD CORPORATION',
       'Tri Sumber Makmur', 'PRESSOL SCHMIERGERÄTE, GMBH',
       'Lipton Ice Tea', 'PT SANTOS JAYA ABADI', 'PT LIWAYWAY',
       'PT KINO INDONESIA TBK', 'KIMIA FARMA', 'Yupi Indo Jelly Gum',
       'ABF', 'PT TRIO MAHA JAYA', 'PT HIDUP BAHAGIA MEDIKA',
       'PT MEDION ARDHIKA BHAKTI', 'Asegar Murni Jaya', 'Suntory',
       'PT DOLPHIN FOOD & BEVERAGES INDUSTRY', 'PT SUMBER BENING LESTARI',
       'CV Permata Kuning', 'PT ESTEH INDONESIA MAKMUR',
       'PT INDOFOOD CBP SUKSES MAKMUR TBK', 'CV.Ake Abadi',
       'Suntory Garuda Beverage', 'PT SAYAP MAS UTAMA',
       'PT INDOMARCO PRISMATAMA', 'SINAR SURYA FOOD',
       'PT JAYA UTAMA SANTIKAH', 'PT BAGUSFOOD', 'APICAL GROUP',
       'PT MANOHARA ASRI', 'Beiersdorf Global AG',
       'Tokai Dharma Indonesia', 'PT PERUSAHAAN INDUSTRI CERES',
       'PT BRONSON PRIMA INDUSTRI', 'PT ANEKA INDOMAKMUR',
       'PT DUA KELINCI', 'Starbucks', 'PT MAYORA INDAH',
       'PT AMERTA INDAH OTSUKA', 'PT SOFTEX INDONESIA', 'Indomaret Group',
       'PT VADCO PROSPER MEGA', 'PT KELLY INTERNATIONAL COSMETICS',
       'PT VICTORY SUPRA SIGARET',
       'PT HALAL NETWORK INTERNATIONAL HERBA PENAWAR ALWAHIDA INDONESIA',
       'PT DARYA VARIA LABORATORIA TBK', 'UNILEVER',
       'Cv. Abadi 3 mandiri', 'Mayora indah',
       'Tupperware India Pvt. Ltd.', 'UD ACP Surabaya', 'PERTAMINA',
       'PT HEINZ ABC INDONESIA', 'Avrio Health LP',
       'CHOYA UMESHU CO., LTD.', 'Mual Tio Maju Bersama', 'Pocari',
       'PT Tirta Fresindo Jaya (MAYORA)', ' PT Mual Tio Maju Bersama',
       'Sapanan General Food Co.', 'Torabika', 'PT Orang Tua',
       'PT Adhitama Sejahtera Abadi', 'PT HM Sampoerna Tbk',
       'Korea Tomorrow & Global Indonesia', 'Wismilak Inti Makmur',
       'Sumatra Tobacco Trading', 'SURYA MAS RAJA TAWON',
       "Muawanah Al Ma'soem Cileunyi", 'Calbe Wings Food',
       'PT TIRTASARI SUMBER MURNI', 'BUDI', 'UD FORMULA',
       'PT LEADON INTERNATIONAL', 'CV CAKRA MAS JAYA',
       'PT ADHITAMA SEJAHTERA ABADI', "PT ARTHA SUMATERA ABADI'S",
       'SIPPIN INDONESIA', 'KFC', 'PT INMAS SUNSHINE',
       'PT MEDAN JAYA PANGAN MUTU', 'PT MIDI UTAMA INDONESIA TBK',
       'Pandan Air Mineral', 'CV Alam Megah Jaya', 'PT Bina Karya Prima',
       'Tirta Sukses Perkasa', 'PT. Dua Kelinci',
       'Bristol-Myers Squibb Company', 'Ultrasakti',
       'PT. Graha Kerindo Utama', 'PT. Santos Jaya Abadi',
       'PT. Sumber Kopi Prima', 'Makmur Group',
       'Cantigi Outdoor Indonesia', 'Kraft Heinz',
       'Lee Kum Kee Company Limite', 'HM SAMPOERNA',
       'Putera Jaya Sakti Perkasa', 'Abirami Soap Works',
       'SOFTEX INDONESIA', 'Heinz ABC Indonesia',
       'Indofood CBP Sukses Makmur', 'Macroprima Panganutama Semarang',
       'Internasional bakery Denpasar', 'Prifood Corporation',
       'Pulau Sambu', 'PT Sariguna Primatirta Tbk',
       'Comfoods Commonwealth Food Inc.', 'ABC PRESIDENT INDONESIA',
       'Ngesti Prima Makmur', 'ANUGRAH PERSADA ALAM'], dtype=object)

#Cleaning kolom layers

In [418]:
df['Layers'].unique()

array(['SL', 'ML', 'Unsure', 'SL '], dtype=object)

In [419]:
filtered_df = df[df['Layers'] == 'SL ']
print(f"\nJumlah 'Layers' dengan 'SL ': {len(filtered_df)}")
display(filtered_df.head())

Jumlah 'Layers' dengan 'SL ': 2

,Brand Name,Parent Company,Type of Product,Type of Material,Layers,Total Count,City,Provinces,Time of Audit,Specifics of Audit
1025,Good Day Coffe,PT Santos Jaya Abadi,FP,PET,SL,1,Kupang,East Nusa Tenggara,2023-09-15 00:00:00,Coast/Shoreline
1035,Roti Beta,Local Brand,FP,LDPE,SL,4,Kupang,East Nusa Tenggara,2023-09-15 00:00:00,Coast/Shoreline

In [420]:
df['Layers'] = df['Layers'].replace(['SL', 'SL '], 'Single Layer')
df['Layers'] = df['Layers'].replace('ML', 'Multi Layer')

print("Unique values di 'Layers':", df['Layers'].unique())
display(df.head())

Unique values di 'Layers': ['Single Layer' 'Multi Layer' 'Unsure']

,Brand Name,Parent Company,Type of Product,Type of Material,Layers,Total Count,City,Provinces,Time of Audit,Specifics of Audit
0,PUTRI PANDA,Putri Panda,FP,PET,Single Layer,6,Cilacap,Central Java,2023-09-09 00:00:00,Coast/Shoreline
1,ABC,Santos Jaya Abadi,FP,PET,Single Layer,12,Cilacap,Central Java,2023-09-09 00:00:00,Coast/Shoreline
2,KAPAL API,Santos Jaya Abadi,FP,PET,Single Layer,3,Cilacap,Central Java,2023-09-09 00:00:00,Coast/Shoreline
3,KOPI GOOD DAY,Santos Jaya Abadi,FP,PET,Single Layer,3,Cilacap,Central Java,2023-09-09 00:00:00,Coast/Shoreline
4,POP MIE,Indofood,FP,PS,Single Layer,1,Cilacap,Central Java,2023-09-09 00:00:00,Coast/Shoreline

#Cleaning kolom type of material

In [421]:
df['Type of Material'].unique()

array(['PET', 'PS', 'O', 'HDPE', 'PVC', 'LDPE', 'PP', nan], dtype=object)

In [422]:
nan_materials = df[df['Type of Material'].isna()]
print(f"Jumlah data NaN di 'Type of Material': {len(nan_materials)}")
display(nan_materials)

Jumlah data NaN di 'Type of Material': 1

,Brand Name,Parent Company,Type of Product,Type of Material,Layers,Total Count,City,Provinces,Time of Audit,Specifics of Audit
1656,KN,UNKNOWN,FP,NaN,Single Layer,2,Denpasar,Bali,2023-09-24 00:00:00,Coast/Shoreline

In [423]:
df['Type of Material'] = df['Type of Material'].fillna('Others')
df['Type of Material'] = df['Type of Material'].replace('O', 'Others')

print("Unique values di 'Type of Material':", df['Type of Material'].unique())
display(df.head())

Unique values di 'Type of Material': ['PET' 'PS' 'Others' 'HDPE' 'PVC' 'LDPE' 'PP']

,Brand Name,Parent Company,Type of Product,Type of Material,Layers,Total Count,City,Provinces,Time of Audit,Specifics of Audit
0,PUTRI PANDA,Putri Panda,FP,PET,Single Layer,6,Cilacap,Central Java,2023-09-09 00:00:00,Coast/Shoreline
1,ABC,Santos Jaya Abadi,FP,PET,Single Layer,12,Cilacap,Central Java,2023-09-09 00:00:00,Coast/Shoreline
2,KAPAL API,Santos Jaya Abadi,FP,PET,Single Layer,3,Cilacap,Central Java,2023-09-09 00:00:00,Coast/Shoreline
3,KOPI GOOD DAY,Santos Jaya Abadi,FP,PET,Single Layer,3,Cilacap,Central Java,2023-09-09 00:00:00,Coast/Shoreline
4,POP MIE,Indofood,FP,PS,Single Layer,1,Cilacap,Central Java,2023-09-09 00:00:00,Coast/Shoreline

#Cleaning kolom type of product

In [424]:
df['Type of Product'].unique()

array(['FP', 'SM', 'PC', 'HP', 'O', 'FG', 'PM', 'FP '], dtype=object)

In [425]:
df['Type of Product'] = df['Type of Product'].replace(['FP','FP '], 'Food Packaging')
df['Type of Product'] = df['Type of Product'].replace('SM', 'Smoking Material')
df['Type of Product'] = df['Type of Product'].replace('PC', 'Personal Care')
df['Type of Product'] = df['Type of Product'].replace('HP', 'Household Product')
df['Type of Product'] = df['Type of Product'].replace('O', 'Others')
df['Type of Product'] = df['Type of Product'].replace('FG', 'Fishing Gear')
df['Type of Product'] = df['Type of Product'].replace('PM', 'Packaging Material')

print("Unique values di 'Type of Product':", df['Type of Product'].unique())
display(df.head())

Unique values di 'Type of Product': ['Food Packaging' 'Smoking Material' 'Personal Care' 'Household Product'
 'Others' 'Fishing Gear' 'Packaging Material']

,Brand Name,Parent Company,Type of Product,Type of Material,Layers,Total Count,City,Provinces,Time of Audit,Specifics of Audit
0,PUTRI PANDA,Putri Panda,Food Packaging,PET,Single Layer,6,Cilacap,Central Java,2023-09-09 00:00:00,Coast/Shoreline
1,ABC,Santos Jaya Abadi,Food Packaging,PET,Single Layer,12,Cilacap,Central Java,2023-09-09 00:00:00,Coast/Shoreline
2,KAPAL API,Santos Jaya Abadi,Food Packaging,PET,Single Layer,3,Cilacap,Central Java,2023-09-09 00:00:00,Coast/Shoreline
3,KOPI GOOD DAY,Santos Jaya Abadi,Food Packaging,PET,Single Layer,3,Cilacap,Central Java,2023-09-09 00:00:00,Coast/Shoreline
4,POP MIE,Indofood,Food Packaging,PS,Single Layer,1,Cilacap,Central Java,2023-09-09 00:00:00,Coast/Shoreline

#Membuat semua Uppercase

In [426]:
# Iterate through all columns in the DataFrame
for col in df.columns:
    # Check if the column's dtype is 'object' (which typically means strings or mixed types)
    if df[col].dtype == 'object':
        # Convert column to string type and then apply .str.upper() for robustness
        # This handles cases where 'object' dtype might contain non-string elements
        df[col] = df[col].astype(str).str.upper()

display(df.head())

,Brand Name,Parent Company,Type of Product,Type of Material,Layers,Total Count,City,Provinces,Time of Audit,Specifics of Audit
0,PUTRI PANDA,PUTRI PANDA,FOOD PACKAGING,PET,SINGLE LAYER,6,CILACAP,CENTRAL JAVA,2023-09-09 00:00:00,COAST/SHORELINE
1,ABC,SANTOS JAYA ABADI,FOOD PACKAGING,PET,SINGLE LAYER,12,CILACAP,CENTRAL JAVA,2023-09-09 00:00:00,COAST/SHORELINE
2,KAPAL API,SANTOS JAYA ABADI,FOOD PACKAGING,PET,SINGLE LAYER,3,CILACAP,CENTRAL JAVA,2023-09-09 00:00:00,COAST/SHORELINE
3,KOPI GOOD DAY,SANTOS JAYA ABADI,FOOD PACKAGING,PET,SINGLE LAYER,3,CILACAP,CENTRAL JAVA,2023-09-09 00:00:00,COAST/SHORELINE
4,POP MIE,INDOFOOD,FOOD PACKAGING,PS,SINGLE LAYER,1,CILACAP,CENTRAL JAVA,2023-09-09 00:00:00,COAST/SHORELINE

In [427]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3795 entries, 0 to 3794
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Brand Name          3795 non-null   object
 1   Parent Company      3795 non-null   object
 2   Type of Product     3795 non-null   object
 3   Type of Material    3795 non-null   object
 4   Layers              3795 non-null   object
 5   Total Count         3795 non-null   object
 6   City                3795 non-null   object
 7   Provinces           3795 non-null   object
 8   Time of Audit       3795 non-null   object
 9   Specifics of Audit  3795 non-null   object
dtypes: object(10)
memory usage: 296.6+ KB

In [428]:
import numpy as np
df['Total Count'] = df['Total Count'].astype(str).str.extract('(\d+)').astype(float)
df['Total Count'] = df['Total Count'].astype('Int64')
df['Time of Audit'] = pd.to_datetime(df['Time of Audit']).dt.date

for col in df.columns:
    if col not in ['Total Count', 'Time of Audit']:
        df[col] = df[col].astype(str)

df.info()
display(df.head())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3795 entries, 0 to 3794
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Brand Name          3795 non-null   object
 1   Parent Company      3795 non-null   object
 2   Type of Product     3795 non-null   object
 3   Type of Material    3795 non-null   object
 4   Layers              3795 non-null   object
 5   Total Count         3794 non-null   Int64
 6   City                3795 non-null   object
 7   Provinces           3795 non-null   object
 8   Time of Audit       3795 non-null   object
 9   Specifics of Audit  3795 non-null   object
dtypes: Int64(1), object(9)
memory usage: 300.3+ KB

,Brand Name,Parent Company,Type of Product,Type of Material,Layers,Total Count,City,Provinces,Time of Audit,Specifics of Audit
0,PUTRI PANDA,PUTRI PANDA,FOOD PACKAGING,PET,SINGLE LAYER,6,CILACAP,CENTRAL JAVA,2023-09-09,COAST/SHORELINE
1,ABC,SANTOS JAYA ABADI,FOOD PACKAGING,PET,SINGLE LAYER,12,CILACAP,CENTRAL JAVA,2023-09-09,COAST/SHORELINE
2,KAPAL API,SANTOS JAYA ABADI,FOOD PACKAGING,PET,SINGLE LAYER,3,CILACAP,CENTRAL JAVA,2023-09-09,COAST/SHORELINE
3,KOPI GOOD DAY,SANTOS JAYA ABADI,FOOD PACKAGING,PET,SINGLE LAYER,3,CILACAP,CENTRAL JAVA,2023-09-09,COAST/SHORELINE
4,POP MIE,INDOFOOD,FOOD PACKAGING,PS,SINGLE LAYER,1,CILACAP,CENTRAL JAVA,2023-09-09,COAST/SHORELINE

In [429]:
df.to_excel('CLEAN BRAND AUDIT 2023.xlsx', index=False)
print("DataFrame exported to 'CLEAN BRAND AUDIT 2023.xlsx' in /content/")

df.to_csv('CLEAN BRAND AUDIT 2023.csv', index=False)
print("DataFrame exported to 'CLEAN BRAND AUDIT 2023.csv' in /content/")

# !cp cleaned_data.xlsx "/content/drive/MyDrive/cleaned_data.xlsx"
# !cp cleaned_data.csv "/content/drive/MyDrive/cleaned_data.csv"
# print("Files copied to Google Drive: cleaned_data.xlsx and cleaned_data.csv")

DataFrame exported to 'CLEAN BRAND AUDIT 2023.xlsx' in /content/
DataFrame exported to 'CLEAN BRAND AUDIT 2023.csv' in /content/